### ISSUE TITLE
:sysinfo fails -  "Uncaught TypeError: converters.objectConverter is not a function"

### ISSUE THREAD

**Issue by meilechh** [neo4j/neo4j-browser#586]
Hi
After upgrading to 3.2 sysinfo command stopped working, the problem appears only when running in HA mode (SINGLE works fine).
This is the error from console: 
```javascript
subscribeToResult.js:42 Uncaught TypeError: converters.objectConverter is not a function
    at objIntToString (webpack:///../shared/services/bolt/boltMappings.js?:80:26)
    at itemIntToString (webpack:///../shared/services/bolt/boltMappings.js?:70:88)
    at eval (webpack:///../shared/services/bolt/boltMappings.js?:75:12)
    at Array.map (native)
    at arrayIntToString (webpack:///../shared/services/bolt/boltMappings.js?:74:14)
    at itemIntToString (webpack:///../shared/services/bolt/boltMappings.js?:67:35)
    at eval (webpack:///./modules/Stream/SysInfoFrame.jsx?:95:78)
    at Array.map (native)
    at SysInfoFrame.flattenAttributes (webpack:///./modules/Stream/SysInfoFrame.jsx?:92:88)
    at eval (webpack:///./modules/Stream/SysInfoFrame.jsx?:176:27)
```
An empty table is displayed on browser, see image bellow: 
![image](https://user-images.githubusercontent.com/5077480/27146098-21528238-5106-11e7-9607-1456ffd45368.png)

After this error, the app stops working, no query can be executed.

**Comment by oskarhane** [comment]
Thanks for the report @meilechh. What Neo4j version are you on?
I believe this should be fixed in Neo4j `3.2.1` (which has Neo4j Browser version`3.0.4`).

**Comment by meilechh** [comment]
I'm on 3.2.1
