### PR TITLE
Fixes mapping issue when using :sysinfo with HA

### LINKED ISSUE #586: :sysinfo fails -  "Uncaught TypeError: converters.objectConverter is not a function"
Hi
After upgrading to 3.2 sysinfo command stopped working, the problem appears only when running in HA mode (SINGLE works fine).
This is the error from console: 
```javascript
subscribeToResult.js:42 Uncaught TypeError: converters.objectConverter is not a function
    at objIntToString (webpack:///../shared/services/bolt/boltMappings.js?:80:26)
    at itemIntToString (webpack:///../shared/services/bolt/boltMappings.js?:70:88)
    at eval (webpack:///../shared/services/bolt/boltMappings.js?:75:12)
    at Array.map (native)
    at arrayIntToString (webpack:///../shared/services/bolt/boltMappings.js?:74:14)
    at itemIntToString (webpack:///../shared/services/bolt/boltMappings.js?:67:35)
    at eval (webpack:///./modules/Stream/SysInfoFrame.jsx?:95:78)
    at Array.map (native)
    at SysInfoFrame.flattenAttributes (webpack:///./modules/Stream/SysInfoFrame.jsx?:92:88)
    at eval (webpack:///./modules/Stream/SysInfoFrame.jsx?:176:27)
```
An empty table is displayed on browser, see image bellow: 
image

After this error, the app stops working, no query can be executed.

### PR DESCRIPTION
**Pull request by pe4cey**
Fixes #586

### CODE REVIEW

**Comment by oskarhane** [comment]
Could you add a test that shows that this error is gone, or is this component hard to run enzyme-compat tests on?

**Comment by pe4cey** [comment]
This is will require some refactoring I was trying to defer until later because on `mount` a child on the `<FrameTemplate />` requires `suber`

**Comment by pe4cey** [comment]
@oskarhane added both component tests and tests around the extracted out logic to support this fix

File: src/browser/modules/Stream/Queries/QueriesFrame.jsx [hunk 1]
```diff
@@ -65,16 +65,13 @@ export class QueriesFrame extends Component {
...
-    return this.props.availableProcedures.includes('dbms.cluster.overview')
-  }
   canListQueries () {
     return this.props.availableProcedures.includes('dbms.listQueries')
   }
 
   getRunningQueries (suppressQuerySuccessMessage = false) {
     this.props.bus.self(
-      (this.isCC()) ? CLUSTER_CYPHER_REQUEST : CYPHER_REQUEST,
+      (this.props.isACausalCluster) ? CLUSTER_CYPHER_REQUEST : CYPHER_REQUEST,
```
Comment (oskarhane) [inline src/browser/modules/Stream/Queries/QueriesFrame.jsx]: How does this get passed to the :queries frame?

Comment (oskarhane) [inline src/browser/modules/Stream/Queries/QueriesFrame.jsx]: Also, you'd need to change the line in `killQueries` below as well, where a check for `this.isCC()` is made.

File: src/browser/modules/Stream/SysInfoFrame/index.jsx [hunk 2]
```diff
@@ -0,0 +1,203 @@
...
+  constructor (props) {
+    super(props)
+    this.state = {
+      error: '',
+      results: false
+    }
+  }
+
+  clusterResponseHandler () {
+    return (res) => {
```
Comment (oskarhane) [inline src/browser/modules/Stream/SysInfoFrame/index.jsx]: Why return function rather than just handle the response directly?
It looks a bit unusual.

File: src/browser/modules/Stream/SysInfoFrame/index.jsx [hunk 3]
```diff
@@ -0,0 +1,203 @@
...
+          ccRecord.role,
+          ccRecord.addresses.join(', '),
+          <Render if={httpUrlForMember.length !== 0}><a taget='_blank' href={httpUrlForMember[0]}>Open</a></Render>
+        ]
+      })
+      this.setState({cc: [{ value: mappedTableComponents }]})
+    }
+  }
+  responseHandler () {
+    return (res) => {
```
Comment (oskarhane) [inline src/browser/modules/Stream/SysInfoFrame/index.jsx]: Same as in `clusterResponseHandler`.
It looks a bit unusual.

File: src/browser/modules/Stream/Queries/QueriesFrame.jsx (hunk 1 above)
Comment (pe4cey) [inline src/browser/modules/Stream/Queries/QueriesFrame.jsx]: This change was by mistake. I didn't plan on changing anything outside of things that affect sysinfo.

**Comment by pe4cey** [comment]
@oskarhane updated

**Comment by oskarhane** [comment]
Very nice changes, lgtm.
